version: "3"
services: 
  dl:
    build: ./
    container_name: "dl"
    # hostname: dl
    restart: always
    # environment: 
    #   - USERNAME="user"
    # volumes:
    #   - type: volume
    #     source: ./../src
    #     target: /home/user/src
    volumes:
      - "./../src:/home/user/src"
    ports:
     - "20022:22"
     - "8888:8888"
# volumes:
#   src: